---
title: "The Ridge Regression"
author: "Yingnan Lyu"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: yes
    toc: true
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{The ridge regression vignette}
%\VignetteEncoding{UTF-8}
\usepackage[utf8]{dplyr}
-->

## The ridge_reg function

Create a vignette, called homework-2, that looks at effect on the out-of-sample mean square error as $\lambda$ varies. Reasonable values can be inferred from the range of the singular values of the training data as
shown in Equation 3.29 in the book. Note that it makes sense to select $\lambda$ values on the log scale.

```{r}
library(bis557)

data("ridge_train")
data("ridge_test")

ridge_mse <- function(formula, lambda, data.train, data.test) {
  fit_ridge <- ridge_reg(formula, lambda, data.train)
  beta <- fit_ridge$coef
  x_test <- model.matrix(formula, ridge_test)
  y_test <- matrix(data.test[,as.character(formula)[2]], ncol=1)
  y_test <- y_test[as.numeric(rownames(x_test)),, drop=FALSE]
  #y_hat <- tcrossprod(x_test, beta)
  y_hat <- x_test %*% beta
  mse <- mean((y_hat - y_test)^2)
}

#lambdas <- seq(10^-5, 10^5, 1000)
#log.lambdas <- log(lambdas, base = 10)
log.lambdas <- seq(-5, 5, 0.1)
lambdas <- 10^log.lambdas

# Calculate MSE for each lambda
mses <- sapply(lambdas, 
               function(lambda) 
                 ridge_mse(y ~ . - 1, lambda, ridge_train, ridge_test))

# Plot MSE against each log(lambda) value
plot(log.lambdas, mses)

# Find lambda that minimize MSE
min.log.lambda <- log.lambdas[which.min(mses)]
min.lambda <- lambdas[which.min(mses)]
```

```{r}
# Zoom in lambda
new.log.lambdas <- seq(min.log.lambda - 0.5, min.log.lambda + 0.5, 0.01)
new.lambdas <- 10^new.log.lambdas

# Calculate MSE for each lambda
new.mses <- sapply(new.lambdas, 
               function(lambda) 
                 ridge_mse(y ~ . - 1, lambda, ridge_train, ridge_test))

# Plot MSE against each log(lambda) value
plot(new.log.lambdas, new.mses)

# Find lambda that minimize MSE
min.new.log.lambda <- new.log.lambdas[which.min(new.mses)]
min.new.lambda <- new.lambdas[which.min(new.mses)]

```
